# Generated by Django 4.2 on 2023-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product')),
                ('content', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-is_published'],
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
