# Generated by Django 4.2 on 2023-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
    ]
