# Generated by Django 4.2 on 2023-04-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_image_projectimage_photo_alter_staff_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='photo',
            new_name='image',
        ),
    ]
