# Generated by Django 4.2 on 2023-04-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_photo_projectimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
    ]
