# Generated by Django 4.2 on 2023-04-06 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
