# Generated by Django 4.2 on 2023-04-06 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=datetime.date.today, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
