# Generated by Django 4.2 on 2023-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='brand',
            field=models.CharField(max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='staff',
            name='size',
            field=models.CharField(max_length=255, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
