# Generated by Django 4.2 on 2023-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staff_brand_staff_size_staff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price $'),
        ),
    ]
