# Generated by Django 4.2 on 2023-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_staff_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
