# Generated by Django 4.2 on 2023-04-10 16:23

from django.db import migrations, models
import django.db.models.deletion
import staff.utils


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_staff_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=staff.utils.get_timestamp_path, verbose_name='Image')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Aditional images',
                'verbose_name_plural': 'Aditional images',
            },
        ),
    ]
