# Generated by Django 4.2 on 2023-04-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_additionalimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimage',
            old_name='bb',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='user_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='user_image', verbose_name='Photo'),
        ),
        migrations.AlterModelTable(
            name='staff',
            table='registration_userprofile',
        ),
    ]
