# Generated by Django 4.2 on 2023-05-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-time_update'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
